# Generated by: Claude Code
"""Session management for kart-chat - save and resume conversations"""

import json
from pathlib import Path
from datetime import datetime

SESSIONS_DIR = Path("artifacts/kart/sessions")
SESSIONS_DIR.mkdir(parents=True, exist_ok=True)

def save_session(history, session_id=None):
    """
    Save conversation history to session file.
    
    Args:
        history: List of conversation messages
        session_id: Optional session ID (generates new if None)
        
    Returns:
        session_id
    """
    if session_id is None:
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        session_id = f"kart-{timestamp}"
    
    session_data = {
        "session_id": session_id,
        "timestamp": datetime.now().isoformat(),
        "history": history,
        "message_count": len(history)
    }
    
    session_file = SESSIONS_DIR / f"{session_id}.json"
    with open(session_file, 'w') as f:
        json.dump(session_data, f, indent=2)
    
    return session_id


def load_session(session_id):
    """
    Load conversation history from session file.
    
    Args:
        session_id: Session ID or partial match
        
    Returns:
        history list or None if not found
    """
    # Try exact match first
    session_file = SESSIONS_DIR / f"{session_id}.json"
    
    # If not found, try partial match
    if not session_file.exists():
        matches = list(SESSIONS_DIR.glob(f"*{session_id}*.json"))
        if matches:
            session_file = matches[0]  # Use first match
        else:
            return None
    
    try:
        with open(session_file, 'r') as f:
            session_data = json.load(f)
        return session_data.get('history', [])
    except Exception as e:
        print(f"Error loading session: {e}")
        return None


def list_sessions(limit=10):
    """
    List recent sessions.
    
    Args:
        limit: Maximum number of sessions to return
        
    Returns:
        List of session info dicts
    """
    sessions = []
    for session_file in sorted(SESSIONS_DIR.glob("*.json"), reverse=True)[:limit]:
        try:
            with open(session_file, 'r') as f:
                data = json.load(f)
            sessions.append({
                "session_id": data.get('session_id'),
                "timestamp": data.get('timestamp'),
                "messages": data.get('message_count', 0),
                "file": session_file.name
            })
        except:
            pass
    
    return sessions


def auto_save_enabled():
    """Check if auto-save is enabled (always True for now)."""
    return True
